name: CI/CD Pipeline

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04


    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (for multi-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
<<<<<<< HEAD
          username: ${{ secrets.DOCKERHUB_USERNAME }}
=======
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
>>>>>>> 503985a47c91c9d2a8699279d969d6babcb9de34
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build Docker image
      - name: Build Docker image
        run: |
<<<<<<< HEAD
          docker build -f Dockerfile.dev -t ${{ secrets.DOCKERHUB_USERNAME }}/seedor-app:latest .
=======
          docker build -f Dockerfile.dev -t sebapaulraj/seedor-app:latest .
>>>>>>> 503985a47c91c9d2a8699279d969d6babcb9de34

      # 5. Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
<<<<<<< HEAD
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/seedor-app:latest
=======
          docker push sebapaulraj/seedor-app:latest
>>>>>>> 503985a47c91c9d2a8699279d969d6babcb9de34

      # 6. (Optional) Deploy via SSH
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
<<<<<<< HEAD
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/seedor-app:latest
            docker stop seedor-container || true
            docker rm seedor-container || true
            docker run -d -p 8000:8000 --name seedor-container ${{ secrets.DOCKERHUB_USERNAME }}/seedor-app:latest
=======
            docker pull sebapaulraj/seedor-app:latest
            docker stop seedor-container || true
            docker rm seedor-container || true
            docker run -d -p 8000:8000 --name seedor-container sebapaulraj/seedor-app:latest
>>>>>>> 503985a47c91c9d2a8699279d969d6babcb9de34
